In [20]:
#EDA
import pandas as pd
import numpy as np
import plotly.express as px
from plotly._subplots import make_subplots
import matplotlib.pyplot as plt
import seaborn as sns

# ML
from mlxtend.frequent_patterns import apriori, association_rules

### Carregar Dados

In [21]:
df = pd.read_csv('./datasets/transations_by_dept.csv', sep=',')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4539 entries, 0 to 4538
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   POS Txn  4539 non-null   uint64
 1   Dept     4539 non-null   str
 2   ID       4539 non-null   int64
 3   Sales U  4539 non-null   int64
dtypes: int64(2), str(1), uint64(1)
memory usage: 142.0 KB

In [23]:
df.head(10)

                POS Txn                       Dept   ID  Sales U
0  16120100160021008773               0261:HOSIERY  250        2
1  16120100160021008773  0634:VITAMINS & HLTH AIDS  102        1
2  16120100160021008773          0879:PET SUPPLIES  158        2
3  16120100160021008773                 0973:CANDY  175        2
4  16120100160021008773               0982:SPIRITS  176        1
5  16120100160021008773                  0983:WINE  177        4
6  16120100160021008773               0991:TOBACCO  179        2
7  16120100160021008774           0597:HEALTH AIDS   93        1
8  16120100160021008774         0604:PERSONAL CARE  100        5
9  16120100160021008775      0819:PRE-RECORDED A/V  135        1

In [24]:
df.tail(10)

                   POS Txn                       Dept   ID  Sales U
4529  16120100160162000841  0857:PC PERIPH/OFFICE ACC  155        1
4530  16120100160162000841                  0931:BATH  165        1
4531  16120100160162000841               0941:BEDDING  167        1
4532  16120100160162000841               0991:TOBACCO  179        1
4533  16120100160162000842     0815:AUDIO ELECTRONICS  132        1
4534  16120100160162000843  0857:PC PERIPH/OFFICE ACC  155        1
4535  16120100160162000845   0395:MENS ATHLETIC SHOES   49        1
4536  16120100160162000845     0815:AUDIO ELECTRONICS  132        1
4537  16120100160162000846    0532:AMERICAN GREETINGS   72        1
4538  16120100160221001467  0066:VENDING/AMUSEMENT MA  242        1

### EDA

In [25]:
df.rename(columns={'POS Txn': 'ID_Transacao', 'Dept': 'Departamento', 'ID': 'ID_Departamento', 'Sales U': 'Qtd_Vendida'}, inplace=True)

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 4390 entries, 0 to 4538
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Transacao     4390 non-null   uint64
 1   Departamento     4390 non-null   str
 2   ID_Departamento  4390 non-null   int64
 3   Qtd_Vendida      4390 non-null   int64
dtypes: int64(2), str(1), uint64(1)
memory usage: 171.5 KB

In [33]:
df['Departamento'].nunique()

156

In [34]:
df['ID_Departamento'].nunique()

156

In [35]:
df['ID_Transacao'].nunique()

1943

In [36]:
len(df.groupby(['ID_Transacao', 'Departamento'])) != len(df)

False

In [31]:
len(df[df['Qtd_Vendida'] <= 0])

149

In [32]:
df = df[df['Qtd_Vendida'] > 0]